dataset: 'cifar10'
drop_rate: 0.1
lambda2: 0.05

# lr_gamma: 0.1
# weight_decay: 0.001
# latent_dim: 128
# kl_y_threshold: 2.3
# entropy_loss: True
# lambda1: 10000
# rampdown_epoch: 200
# rampup_epoch: 100